" Vim color file - corporation_mod
" Generated by http://bytefluent.com/vivify 2015-10-30
set background=dark
if version > 580
	hi clear
	if exists("syntax_on")
		syntax reset
	endif
endif

set t_Co=256
let g:colors_name = "test"

"BG 	            30	30	30	 	1E	1E	1E	#1E1E1E
"line-hightlight    15	15	15	 	0F	0F	0F	#0F0F0F
"keyword 	        86	156	214	 	56	9C	D6	#569CD6
"type 	            86	156	214	 	56	9C	D6	#569CD6
"statement 	        218	218	218	 	DA	DA	DA	#DADADA
"cursor 	        220	220	220	 	DC	DC	DC	#DCDCDC
"usertype 	        78	201	176	 	4E	C9	B0	#4EC9B0
"define keyword 	155	155	155	 	9B	9B	9B	#9B9B9B
"define name 	    189	99	197	 	BD	63	C5	#BD63C5
"include file       214	157	119	 	D6	9D	77	#D69D77
"string 	        214	157	133	 	D6	9D	85	#D69D85
"operator 	        180	180	180	 	B4	B4	B4	#B4B4B4
"number 	        181	206	168	 	B5	CE	A8	#B5CEA8
"comment 	        87	166	74	 	57	A6	4A	#57A64A
"numbers 	        43	145	175	 	2B	91	AF	#2B91AF
"search bg 	        14	58	108	 	0E	3A	6C	#0E3A6C
"search fg 	        200	200	200	 	C8	C8	C8	#C8C8C8

hi Normal           guibg=#1E1E1E   guifg=#DADADA   gui=NONE
hi CursorLine       guibg=#282828   guifg=NONE      gui=NONE
hi Cursor           guibg=#264F78   guifg=NONE      gui=NONE   
hi Visual           guibg=#264F78   guifg=NONE      gui=NONE   
hi LineNr           guibg=NONE      guifg=#2B91AF   gui=NONE
hi Folded           guibg=#264F78   guifg=#DADADA   gui=ITALIC
hi StatusLine       guibg=#468CC6   guifg=#1E1E1E   gui=bold
hi StatusLineNC     guibg=#468CC6   guifg=#1E1E1E   gui=bold

hi Comment          guibg=NONE      guifg=#57A64A   gui=NONE
hi Underlined       guibg=NONE      guifg=#57A64A   gui=UNDERLINE
hi Ignore           guibg=NONE      guifg=#57A64A   gui=NONE
hi Error            guibg=NONE      guifg=#57A64A   gui=BOLD
hi Todo             guibg=NONE      guifg=#57A64A   gui=BOLD,UNDERLINE

hi Constant         guibg=NONE      guifg=#DADADA   gui=NONE
hi String           guibg=NONE      guifg=#D69D85   gui=NONE
hi Character        guibg=NONE      guifg=#D69D85   gui=NONE
hi Number           guibg=NONE      guifg=#B5CEA8   gui=NONE
hi Boolean          guibg=NONE      guifg=#B5CEA8   gui=NONE
hi Float            guibg=NONE      guifg=#B5CEA8   gui=NONE

hi Identifier       guibg=NONE      guifg=NONE      gui=BOLD
hi Function         guibg=NONE      guifg=NONE      gui=BOLD,ITALIC

hi Statement        guibg=NONE      guifg=#569CD6   gui=BOLD
hi Conditional      guibg=NONE      guifg=#569CD6   gui=BOLD
hi Repeat           guibg=NONE      guifg=#569CD6   gui=BOLD
hi Label            guibg=NONE      guifg=#569CD6   gui=BOLD
hi Operator         guibg=NONE      guifg=#B4B4B4   gui=BOLD
hi Keyword          guibg=NONE      guifg=#569CD6   gui=BOLD
hi Exception        guibg=NONE      guifg=#569CD6   gui=BOLD

hi PreProc          guifg=#BD63C5   guibg=NONE      gui=NONE
hi Include          guifg=#BD63C5   guibg=NONE      gui=NONE
hi Define           guifg=#BD63C5   guibg=NONE      gui=NONE
hi Macro            guifg=#BD63C5   guibg=NONE      gui=NONE
hi PreCondit        guifg=#BD63C5   guibg=NONE      gui=NONE

hi Type             guibg=NONE      guifg=#569CD6   gui=NONE
hi StorageClass     guibg=NONE      guifg=#569CD6   gui=NONE
hi Structure        guibg=NONE      guifg=#569CD6   gui=NONE
hi Typedef          guibg=NONE      guifg=#569CD6   gui=NONE


hi Special          guibg=NONE      guifg=#B4B4B4   gui=BOLD
hi SpecialChar      guibg=NONE      guifg=#D69D85   gui=NONE
hi Tag              guibg=NONE      guifg=NONE      gui=UNDERLINE
hi Delimiter        guibg=NONE      guifg=#B4B4B4   gui=BOLD
hi SpecialComment   guibg=NONE      guifg=#57A64A   gui=NONE
hi Debug            guibg=NONE      guifg=#57A64A   gui=BOLD


"  hi CursorColumn guifg=NONE guibg=#0F0F0F guisp=#0F0F0F gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE
"  hi Cursor guifg=#1E1E1E guibg=#F9F9F9 guisp=#F9F9F9 gui=NONE ctermfg=235 ctermbg=15 cterm=NONE



"  "hi CTagsMember -- no settings --
"  "hi CTagsGlobalConstant -- no settings --
"  "hi Ignore -- no settings --
"  hi Normal guifg=#DCDCDC guibg=#1E1E1E guisp=#1E1E1E gui=NONE ctermfg=189 ctermbg=235 cterm=NONE
"  "hi CTagsImport -- no settings --
"  "hi CTagsGlobalVariable -- no settings --
"  "hi EnumerationValue -- no settings --
"  "hi Union -- no settings --
"  "hi Question -- no settings --
"  "hi EnumerationName -- no settings --
"  "hi DefinedName -- no settings --
"  "hi LocalVariable -- no settings --
"  "hi CTagsClass -- no settings --
"  "hi clear -- no settings --
"  hi IncSearch guifg=#1E1E1E guibg=#BD9800 guisp=#BD9800 gui=NONE ctermfg=235 ctermbg=1 cterm=NONE
"  hi WildMenu guifg=NONE guibg=#A1A6A8 guisp=#A1A6A8 gui=NONE ctermfg=NONE ctermbg=248 cterm=NONE
"  hi SignColumn guifg=#1E1E1E guibg=#536991 guisp=#536991 gui=NONE ctermfg=235 ctermbg=60 cterm=NONE
"  hi SpecialComment guifg=#BD9800 guibg=NONE guisp=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
"  hi Typedef guifg=#536991 guibg=NONE guisp=NONE gui=bold ctermfg=60 ctermbg=NONE cterm=bold
"  hi Title guifg=#DCDCDC guibg=#1E1E1E guisp=#1E1E1E gui=bold ctermfg=189 ctermbg=235 cterm=bold
"  hi Folded guifg=#1E1E1E guibg=#A1A6A8 guisp=#A1A6A8 gui=italic ctermfg=235 ctermbg=248 cterm=NONE
"  hi Include guifg=#BD9800 guibg=NONE guisp=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
"  hi TabLineSel guifg=#1E1E1E guibg=#BD9800 guisp=#BD9800 gui=bold ctermfg=235 ctermbg=1 cterm=bold
"  hi NonText guifg=#5E6C70 guibg=NONE guisp=NONE gui=italic ctermfg=66 ctermbg=NONE cterm=NONE
"  hi ErrorMsg guifg=#A1A6A8 guibg=#912C00 guisp=#912C00 gui=NONE ctermfg=248 ctermbg=88 cterm=NONE
"  hi Debug guifg=#BD9800 guibg=NONE guisp=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
"  hi PMenuSbar guifg=NONE guibg=#848688 guisp=#848688 gui=NONE ctermfg=NONE ctermbg=102 cterm=NONE
"  hi Identifier guifg=#BD9800 guibg=NONE guisp=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
"  hi SpecialChar guifg=#BD9800 guibg=NONE guisp=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
"  hi Conditional guifg=#BD9800 guibg=NONE guisp=NONE gui=bold ctermfg=1 ctermbg=NONE cterm=bold
"  hi Todo guifg=#DCDCDC guibg=#BD9800 guisp=#BD9800 gui=NONE ctermfg=189 ctermbg=1 cterm=NONE
"  hi Special guifg=#BD9800 guibg=NONE guisp=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
"  hi LineNr guifg=#BD9800 guibg=NONE guisp=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
"  hi StatusLine guifg=#1E1E1E guibg=#BD9800 guisp=#BD9800 gui=bold ctermfg=235 ctermbg=1 cterm=bold
"  hi StatusLineNC guifg=#1E1E1E guibg=#5E6C70 guisp=#5E6C70 gui=bold ctermfg=235 ctermbg=66 cterm=bold
"  hi Label guifg=#BD9800 guibg=NONE guisp=NONE gui=bold ctermfg=1 ctermbg=NONE cterm=bold
"  hi PMenuSel guifg=#1E1E1E guibg=#BD9800 guisp=#BD9800 gui=NONE ctermfg=235 ctermbg=1 cterm=NONE
"  hi Search guifg=#1E1E1E guibg=#BD9800 guisp=#BD9800 gui=NONE ctermfg=235 ctermbg=1 cterm=NONE
"  hi Delimiter guifg=#BD9800 guibg=NONE guisp=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
"  hi Statement guifg=#BD9800 guibg=NONE guisp=NONE gui=bold ctermfg=1 ctermbg=NONE cterm=bold
"  hi SpellRare guifg=#DCDCDC guibg=#1E1E1E guisp=#1E1E1E gui=underline ctermfg=189 ctermbg=235 cterm=underline
"  hi Comment guifg=#56A64A guibg=NONE guisp=NONE gui=NONE ctermfg=66 ctermbg=NONE cterm=NONE
"  hi Character guifg=#A1A6A8 guibg=NONE guisp=NONE gui=NONE ctermfg=248 ctermbg=NONE cterm=NONE
"  hi Float guifg=#A1A6A8 guibg=NONE guisp=NONE gui=NONE ctermfg=248 ctermbg=NONE cterm=NONE
"  hi Number guifg=#A1A6A8 guibg=NONE guisp=NONE gui=NONE ctermfg=248 ctermbg=NONE cterm=NONE
"  hi Boolean guifg=#A1A6A8 guibg=NONE guisp=NONE gui=NONE ctermfg=248 ctermbg=NONE cterm=NONE
"  hi Operator guifg=#BD9800 guibg=NONE guisp=NONE gui=bold ctermfg=1 ctermbg=NONE cterm=bold
"  hi TabLineFill guifg=#1E1E1E guibg=#5E6C70 guisp=#5E6C70 gui=bold ctermfg=235 ctermbg=66 cterm=bold
"  hi WarningMsg guifg=#A1A6A8 guibg=#912C00 guisp=#912C00 gui=NONE ctermfg=248 ctermbg=88 cterm=NONE
"  hi VisualNOS guifg=#1E1E1E guibg=#DCDCDC guisp=#DCDCDC gui=underline ctermfg=235 ctermbg=189 cterm=underline
"  hi ModeMsg guifg=#F9F9F9 guibg=#1E1E1E guisp=#1E1E1E gui=bold ctermfg=15 ctermbg=235 cterm=bold
"  hi CursorLine guifg=NONE guibg=#0F0F0F guisp=#0F0F0F gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE
"  hi CursorColumn guifg=NONE guibg=#0F0F0F guisp=#0F0F0F gui=NONE ctermfg=NONE ctermbg=236 cterm=NONE
"  hi Cursor guifg=#1E1E1E guibg=#F9F9F9 guisp=#F9F9F9 gui=NONE ctermfg=235 ctermbg=15 cterm=NONE
"  hi Function guifg=#536991 guibg=NONE guisp=NONE gui=bold ctermfg=60 ctermbg=NONE cterm=bold
"  hi FoldColumn guifg=#1E1E1E guibg=#A1A6A8 guisp=#A1A6A8 gui=italic ctermfg=235 ctermbg=248 cterm=NONE
"  hi Visual guifg=#1E1E1E guibg=#DCDCDC guisp=#DCDCDC gui=NONE ctermfg=235 ctermbg=189 cterm=NONE
"  hi MoreMsg guifg=#BD9800 guibg=NONE guisp=NONE gui=bold ctermfg=1 ctermbg=NONE cterm=bold
"  hi SpellCap guifg=#DCDCDC guibg=#1E1E1E guisp=#1E1E1E gui=underline ctermfg=189 ctermbg=235 cterm=underline
"  hi VertSplit guifg=#1E1E1E guibg=#5E6C70 guisp=#5E6C70 gui=bold ctermfg=235 ctermbg=66 cterm=bold
"  hi Exception guifg=#BD9800 guibg=NONE guisp=NONE gui=bold ctermfg=1 ctermbg=NONE cterm=bold
"  hi SpellLocal guifg=#DCDCDC guibg=#1E1E1E guisp=#1E1E1E gui=underline ctermfg=189 ctermbg=235 cterm=underline
"  hi Error guifg=#A1A6A8 guibg=#912C00 guisp=#912C00 gui=NONE ctermfg=248 ctermbg=88 cterm=NONE
"  hi PMenu guifg=#1E1E1E guibg=#5E6C70 guisp=#5E6C70 gui=NONE ctermfg=235 ctermbg=66 cterm=NONE
"  hi SpecialKey guifg=#5E6C70 guibg=NONE guisp=NONE gui=italic ctermfg=66 ctermbg=NONE cterm=NONE
"  hi Constant guifg=#A1A6A8 guibg=NONE guisp=NONE gui=NONE ctermfg=248 ctermbg=NONE cterm=NONE
"  hi Tag guifg=#BD9800 guibg=NONE guisp=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
"  hi String guifg=#A1A6A8 guibg=NONE guisp=NONE gui=NONE ctermfg=248 ctermbg=NONE cterm=NONE
"  hi PMenuThumb guifg=NONE guibg=#a4a6a8 guisp=#a4a6a8 gui=NONE ctermfg=NONE ctermbg=248 cterm=NONE
"  hi MatchParen guifg=#BD9800 guibg=NONE guisp=NONE gui=bold ctermfg=1 ctermbg=NONE cterm=bold
"  hi Repeat guifg=#BD9800 guibg=NONE guisp=NONE gui=bold ctermfg=1 ctermbg=NONE cterm=bold
"  hi SpellBad guifg=#DCDCDC guibg=#1E1E1E guisp=#1E1E1E gui=underline ctermfg=189 ctermbg=235 cterm=underline
"  hi Directory guifg=#536991 guibg=NONE guisp=NONE gui=bold ctermfg=60 ctermbg=NONE cterm=bold
"  hi Underlined guifg=#DCDCDC guibg=#1E1E1E guisp=#1E1E1E gui=underline ctermfg=189 ctermbg=235 cterm=underline
"  hi TabLine guifg=#1E1E1E guibg=#5E6C70 guisp=#5E6C70 gui=bold ctermfg=235 ctermbg=66 cterm=bold
"  hi cursorim guifg=#1E1E1E guibg=#536991 guisp=#536991 gui=NONE ctermfg=235 ctermbg=60 cterm=NONE
"
"  hi Macro     guifg=#FFB0FF guibg=NONE guisp=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
"  hi PreProc   guifg=#FFB0FF guibg=NONE guisp=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
"  hi Define    guifg=#FFB0FF guibg=NONE guisp=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
"  hi PreCondit guifg=#FFB0FF guibg=NONE guisp=NONE gui=NONE ctermfg=1 ctermbg=NONE cterm=NONE
"
"  hi Keyword      guifg=#BD9800 guibg=NONE guisp=NONE gui=bold ctermfg=1  ctermbg=NONE cterm=bold
"  hi Type         guifg=#536991 guibg=NONE guisp=NONE gui=bold ctermfg=60 ctermbg=NONE cterm=bold
"  hi Structure    guifg=#BD9800 guibg=NONE guisp=NONE gui=bold ctermfg=1  ctermbg=NONE cterm=bold
"  hi StorageClass guifg=#BD9800 guibg=NONE guisp=NONE gui=bold ctermfg=1  ctermbg=NONE cterm=bold
"
"  hi DiffDelete   guifg=NONE guibg=#492224 guisp=#492224 gui=NONE ctermfg=NONE ctermbg=52   cterm=NONE
"  hi DiffChange   guifg=NONE guibg=NONE    guisp=NONE    gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
"  hi DiffText     guifg=NONE guibg=#4a2a4a guisp=#4a2a4a gui=NONE ctermfg=NONE ctermbg=52   cterm=NONE
"  hi DiffAdd      guifg=NONE guibg=#306d30 guisp=#306d30 gui=NONE ctermfg=NONE ctermbg=236  cterm=NONE

hi DiffAdd          ctermbg=235  ctermfg=108  guibg=#262626 guifg=#87af87 cterm=reverse        gui=reverse
hi DiffChange       ctermbg=235  ctermfg=103  guibg=#262626 guifg=#8787af cterm=reverse        gui=reverse
hi DiffDelete       ctermbg=235  ctermfg=131  guibg=#262626 guifg=#af5f5f cterm=reverse        gui=reverse
hi DiffText         ctermbg=235  ctermfg=208  guibg=#262626 guifg=#ff8700 cterm=reverse        gui=reverse

hi link diffBDiffer              WarningMsg
hi link diffCommon               WarningMsg
hi link diffDiffer               WarningMsg
hi link diffIdentical            WarningMsg
hi link diffIsA                  WarningMsg
hi link diffNoEOL                WarningMsg
hi link diffOnly                 WarningMsg
hi link diffRemoved              WarningMsg
hi link diffAdded                String
